ACTION_TO_IDX = {
    'CZESC': 0,
    'DZIEN DOBRY': 1,
    'DOBRY WIECZOR': 2,
    'JAK SIE CZUJESZ': 3,
    'DOBRZE': 4,
    'BARDZO DOBRZE': 5,
    'DO WIDZENIA': 6,
    'DOBRANOC': 7,
    'JA': 8,
    'TY': 9,
    'ON_ONA': 10,
    'ONI': 11,
    'MY': 12,
    'MAM': 13,
    'NAZWISKO': 14,
    'IMIE': 15,
    'MIGOWY ZNAK': 16,
    'GLUCHY': 17,
    'SLYSZACY': 18,
    'MASZ': 19,
    'JEST': 20,
    'ZONA_MAZ': 21,
    'POZNAC': 22,
    'TWOJ_SWOJ': 23,
    'DZIEKOWAC': 24,
    'MEZCZYZNA': 25,
    'PRZYJACIEL': 26,
    'DZIECI': 27,
    'ROZMAWIAC': 28,
    'KOBIETA': 29,
    'WAS': 30,
    'JEGO_JEJ': 31,
    'PRZEPRASZAC': 32,
    'PANI': 33,
    'SZKOLA': 34,
    'PAN': 35,
    'MOJ_SWOJ': 36,
}
